Detect parsing errors and raise an exception if fatal errors occur
+ Don't stop parsing unless fatal errors occur. Theoretically, header
  files shouldn't encounter any errors at all unless they are things
  like wlroot's unstable interface warning like the following:
  error: "Add -DWLR_USE_UNSTABLE to enable unstable wlroots features"
+ Stop at fatal errors, as missing include files will definitely
  cause bindings to be generated incorrectly.